//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyunCRM.DataBaseLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firmalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Firmalar()
        {
            this.MusteriFirmalari = new HashSet<MusteriFirmalari>();
            this.MusteriGorusmeleri = new HashSet<MusteriGorusmeleri>();
        }
    
        public int FirmalarID { get; set; }
        public string FirmaAdi { get; set; }
        public bool FirmaDurumu { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime FirmaKayitTarihi { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
    
        public virtual Personeller Personeller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusteriFirmalari> MusteriFirmalari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusteriGorusmeleri> MusteriGorusmeleri { get; set; }
    }
}
