//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyunCRM.DataBaseLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gelirler
    {
        public int GelirlerID { get; set; }
        public int GelirTipID { get; set; }
        public Nullable<decimal> GelirMiktari { get; set; }
        public string GelirAciklama { get; set; }
        public Nullable<decimal> UrunSatisFiyati { get; set; }
        public Nullable<System.DateTime> GelirislemSaati { get; set; }
    
        public virtual GelirTipleri GelirTipleri { get; set; }
    }
}
