//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyunCRM.DataBaseLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giderler
    {
        public int GiderlerID { get; set; }
        public int GiderTipID { get; set; }
        public Nullable<decimal> GiderMiktar { get; set; }
        public string Aciklama { get; set; }
        public Nullable<decimal> UrunalisFiyati { get; set; }
        public Nullable<System.DateTime> GiderislemSaati { get; set; }
    
        public virtual GiderTipleri GiderTipleri { get; set; }
    }
}
