//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyunCRM.DataBaseLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriTalepleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MusteriTalepleri()
        {
            this.MusteriTalepDetaylar = new HashSet<MusteriTalepDetaylar>();
        }
    
        public int MusteriTalepleriID { get; set; }
        public System.DateTime TalepTarihi { get; set; }
        public Nullable<System.DateTime> TalepTeslimTarihi { get; set; }
        public string Aciklama { get; set; }
        public int PersonelID { get; set; }
        public int MusteriID { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusteriTalepDetaylar> MusteriTalepDetaylar { get; set; }
        public virtual Personeller Personeller { get; set; }
    }
}
