//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyunCRM.DataBaseLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriFirmalari
    {
        public int MusteriFirmalariID { get; set; }
        public int MusteriID { get; set; }
        public int FirmaID { get; set; }
        public System.DateTime KayitTarihi { get; set; }
    
        public virtual Firmalar Firmalar { get; set; }
        public virtual Musteriler Musteriler { get; set; }
    }
}
