//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyunCRM.DataBaseLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriTalepDetaylar
    {
        public int MusteriTalepDetaylarID { get; set; }
        public int MusteriTalepID { get; set; }
        public int UrunID { get; set; }
        public decimal Fiyat { get; set; }
        public decimal Miktar { get; set; }
        public string Aciklama { get; set; }
    
        public virtual MusteriTalepleri MusteriTalepleri { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
