//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyunCRM.DataBaseLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriOdemeleri
    {
        public int MusteriOdemeleriID { get; set; }
        public int OdemeSekliID { get; set; }
        public System.DateTime OdemeTarihi { get; set; }
        public decimal OdenecekMiktar { get; set; }
        public string Aciklama { get; set; }
        public int MusteriID { get; set; }
        public string BankaAdi { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        public virtual OdemeSekli OdemeSekli { get; set; }
    }
}
