//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyunCRM.DataBaseLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriSiparisleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MusteriSiparisleri()
        {
            this.MusteriSiparisDetay = new HashSet<MusteriSiparisDetay>();
        }
    
        public int MusteriSiparisleriID { get; set; }
        public int MusteriID { get; set; }
        public int PersonelID { get; set; }
        public System.DateTime SiparisVerilisTarihi { get; set; }
        public Nullable<System.DateTime> SiparisTeslimTarihi { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusteriSiparisDetay> MusteriSiparisDetay { get; set; }
        public virtual Personeller Personeller { get; set; }
    }
}
