//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyunCRM.DataBaseLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelGirisCikislar
    {
        public int PersonelGirisCikislarID { get; set; }
        public int PersonelID { get; set; }
        public System.DateTime iseBaslamaTarihi { get; set; }
        public Nullable<System.DateTime> istenCikisTarihi { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Personeller Personeller { get; set; }
    }
}
