//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyunCRM.DataBaseLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personeller()
        {
            this.Firmalar = new HashSet<Firmalar>();
            this.MusteriGorusmeleri = new HashSet<MusteriGorusmeleri>();
            this.MusteriSiparisleri = new HashSet<MusteriSiparisleri>();
            this.MusteriTalepleri = new HashSet<MusteriTalepleri>();
            this.MusteriToplantilari = new HashSet<MusteriToplantilari>();
            this.PersonelGirisCikislar = new HashSet<PersonelGirisCikislar>();
            this.PersonelGunlukTakip = new HashSet<PersonelGunlukTakip>();
            this.Personelizinleri = new HashSet<Personelizinleri>();
            this.PersonellerinCalistigiDepartmanlar = new HashSet<PersonellerinCalistigiDepartmanlar>();
            this.PersonelMesaileri = new HashSet<PersonelMesaileri>();
            this.PersonelPrimler = new HashSet<PersonelPrimler>();
            this.PersonelToplantilari = new HashSet<PersonelToplantilari>();
            this.PesonelMaasBilgiler = new HashSet<PesonelMaasBilgiler>();
            this.Uyeler = new HashSet<Uyeler>();
            this.Yonetim = new HashSet<Yonetim>();
        }
    
        public int PersonellerID { get; set; }
        public string TC { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public string Email { get; set; }
        public string MedeniHali { get; set; }
        public string Cinsiyet { get; set; }
        public string DogumYeri { get; set; }
        public System.DateTime DogumTarihi { get; set; }
        public string Resim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Firmalar> Firmalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusteriGorusmeleri> MusteriGorusmeleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusteriSiparisleri> MusteriSiparisleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusteriTalepleri> MusteriTalepleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusteriToplantilari> MusteriToplantilari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelGirisCikislar> PersonelGirisCikislar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelGunlukTakip> PersonelGunlukTakip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personelizinleri> Personelizinleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonellerinCalistigiDepartmanlar> PersonellerinCalistigiDepartmanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelMesaileri> PersonelMesaileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelPrimler> PersonelPrimler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelToplantilari> PersonelToplantilari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PesonelMaasBilgiler> PesonelMaasBilgiler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uyeler> Uyeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yonetim> Yonetim { get; set; }
    }
}
