//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyunCRM.DataBaseLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taksitler
    {
        public int TaksitlerID { get; set; }
        public string Taksit1 { get; set; }
        public Nullable<System.DateTime> Tarih1 { get; set; }
        public string Taksit2 { get; set; }
        public Nullable<System.DateTime> Tarih2 { get; set; }
        public string Taksit3 { get; set; }
        public Nullable<System.DateTime> Tarih3 { get; set; }
        public string Taksit4 { get; set; }
        public Nullable<System.DateTime> Tarih4 { get; set; }
        public string Taksit5 { get; set; }
        public Nullable<System.DateTime> Tarih5 { get; set; }
    }
}
