//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyunCRM.DataBaseLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tedarikciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tedarikciler()
        {
            this.TedarikEdilenUrunler = new HashSet<TedarikEdilenUrunler>();
        }
    
        public int TedarikcilerID { get; set; }
        public string TedarikciSirketAdi { get; set; }
        public string TedarikciKontakAdi { get; set; }
        public string TedarikciKontakUnvani { get; set; }
        public string Adres { get; set; }
        public string Ulkesi { get; set; }
        public string Sehir { get; set; }
        public string PostaKodu { get; set; }
        public string Telefon { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public System.DateTime TedarikciOlmaTarihi { get; set; }
        public bool Durumu { get; set; }
        public string Aciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TedarikEdilenUrunler> TedarikEdilenUrunler { get; set; }
    }
}
