//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyunCRM.DataBaseLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TedarikEdilenUrunler
    {
        public int TedarikEdilenUrunlerID { get; set; }
        public int UrunID { get; set; }
        public System.DateTime TedarikTarihi { get; set; }
        public decimal Fiyat { get; set; }
        public string Aciklama { get; set; }
        public int TedarikciID { get; set; }
    
        public virtual Tedarikciler Tedarikciler { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
