//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyunCRM.DataBaseLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToplantiTanimi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToplantiTanimi()
        {
            this.MusteriToplantilari = new HashSet<MusteriToplantilari>();
            this.PersonelToplantilari = new HashSet<PersonelToplantilari>();
        }
    
        public int ToplantiTanimlarID { get; set; }
        public string ToplantiTanimi1 { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public string Aciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusteriToplantilari> MusteriToplantilari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelToplantilari> PersonelToplantilari { get; set; }
    }
}
