//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyunCRM.DataBaseLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.MusteriSiparisDetay = new HashSet<MusteriSiparisDetay>();
            this.MusteriTalepDetaylar = new HashSet<MusteriTalepDetaylar>();
            this.Resimler = new HashSet<Resimler>();
            this.TedarikEdilenUrunler = new HashSet<TedarikEdilenUrunler>();
            this.UrunStoklari = new HashSet<UrunStoklari>();
        }
    
        public int UrunlerID { get; set; }
        public string UrunAdi { get; set; }
        public int UrunKategoriID { get; set; }
        public string BirimBasinaMiktar { get; set; }
        public decimal BirimFiyati { get; set; }
        public string Aciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusteriSiparisDetay> MusteriSiparisDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusteriTalepDetaylar> MusteriTalepDetaylar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resimler> Resimler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TedarikEdilenUrunler> TedarikEdilenUrunler { get; set; }
        public virtual UrunKategorileri UrunKategorileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunStoklari> UrunStoklari { get; set; }
    }
}
