//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyunCRM.DataBaseLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        public int UyelerID { get; set; }
        public int PersonelID { get; set; }
        public int YetkiID { get; set; }
        public string UyeAdi { get; set; }
        public string Sifre { get; set; }
        public bool Durum { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Personeller Personeller { get; set; }
        public virtual Yetkiler Yetkiler { get; set; }
    }
}
